"""Potential-situation classifications; none are trading commands."""

from enum import StrEnum


class SetupType(StrEnum):
    SCALP_TREND_PULLBACK = "SCALP_TREND_PULLBACK"
    SCALP_BREAKOUT = "SCALP_BREAKOUT"
    SCALP_BREAKOUT_RETEST = "SCALP_BREAKOUT_RETEST"
    SCALP_RANGE_BOUNCE = "SCALP_RANGE_BOUNCE"
    SCALP_LIQUIDITY_SWEEP = "SCALP_LIQUIDITY_SWEEP"
    SCALP_MOMENTUM_CONTINUATION = "SCALP_MOMENTUM_CONTINUATION"
    SCALP_COMPRESSION_BREAK = "SCALP_COMPRESSION_BREAK"
    REVERSAL_START = "REVERSAL_START"
    BREAKOUT_CONTINUATION = "BREAKOUT_CONTINUATION"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"
    RANGE_REJECTION = "RANGE_REJECTION"
    PULLBACK_CONTINUATION = "PULLBACK_CONTINUATION"
    FALSE_BREAKOUT_REVERSAL = "FALSE_BREAKOUT_REVERSAL"
    MOMENTUM_EXHAUSTION = "MOMENTUM_EXHAUSTION"
    RANGE_CONTINUATION = "RANGE_CONTINUATION"
    TREND_CONTINUATION = "TREND_CONTINUATION"
    LATE_ENTRY_REJECTED = "LATE_ENTRY_REJECTED"
    CHOP_FILTERED = "CHOP_FILTERED"
    NO_SETUP = "NO_SETUP"
