"""Potential-situation classifications; none are trading commands."""

from enum import StrEnum


class SetupType(StrEnum):
    REVERSAL_START = "REVERSAL_START"
    BREAKOUT_CONTINUATION = "BREAKOUT_CONTINUATION"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"
    RANGE_REJECTION = "RANGE_REJECTION"
    PULLBACK_CONTINUATION = "PULLBACK_CONTINUATION"
    FALSE_BREAKOUT_REVERSAL = "FALSE_BREAKOUT_REVERSAL"
    MOMENTUM_EXHAUSTION = "MOMENTUM_EXHAUSTION"
    RANGE_CONTINUATION = "RANGE_CONTINUATION"
    TREND_CONTINUATION = "TREND_CONTINUATION"
    LATE_ENTRY_REJECTED = "LATE_ENTRY_REJECTED"
    CHOP_FILTERED = "CHOP_FILTERED"
    NO_SETUP = "NO_SETUP"
