"""Paper-only plan classifications."""

from enum import StrEnum


class PaperPlanType(StrEnum):
    BREAKOUT_CONTINUATION_PAPER_PLAN = "BREAKOUT_CONTINUATION_PAPER_PLAN"
    TREND_CONTINUATION_PAPER_PLAN = "TREND_CONTINUATION_PAPER_PLAN"
    PULLBACK_CONTINUATION_PAPER_PLAN = "PULLBACK_CONTINUATION_PAPER_PLAN"
    RANGE_REJECTION_PAPER_PLAN = "RANGE_REJECTION_PAPER_PLAN"
    FALSE_BREAKOUT_REVERSAL_PAPER_PLAN = "FALSE_BREAKOUT_REVERSAL_PAPER_PLAN"
    NO_PAPER_PLAN = "NO_PAPER_PLAN"


STRATEGY_TO_PAPER_PLAN = {
    "BREAKOUT_CONTINUATION_RESEARCH": PaperPlanType.BREAKOUT_CONTINUATION_PAPER_PLAN.value,
    "TREND_CONTINUATION_RESEARCH": PaperPlanType.TREND_CONTINUATION_PAPER_PLAN.value,
    "PULLBACK_CONTINUATION_RESEARCH": PaperPlanType.PULLBACK_CONTINUATION_PAPER_PLAN.value,
    "RANGE_REJECTION_RESEARCH": PaperPlanType.RANGE_REJECTION_PAPER_PLAN.value,
    "FALSE_BREAKOUT_REVERSAL_RESEARCH": PaperPlanType.FALSE_BREAKOUT_REVERSAL_PAPER_PLAN.value,
    "NO_STRATEGY": PaperPlanType.NO_PAPER_PLAN.value,
}


def paper_plan_type_for(strategy_type: str | None) -> str:
    return STRATEGY_TO_PAPER_PLAN.get(str(strategy_type or ""), PaperPlanType.NO_PAPER_PLAN.value)
