"""Stable string vocabularies for the execution-intent boundary."""

from enum import StrEnum


class ExecutionMode(StrEnum):
    PAPER = "PAPER"
    DRY_RUN = "DRY_RUN"
    LIVE = "LIVE"


class ExecutionSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class ExecutionOrderType(StrEnum):
    MARKET_INTENT = "MARKET_INTENT"
    LIMIT_INTENT = "LIMIT_INTENT"


class ExecutionIntentStatus(StrEnum):
    READY = "READY"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"
    DISABLED = "DISABLED"


class ExecutionAcknowledgementStatus(StrEnum):
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"
    DISABLED = "DISABLED"


class ExecutionReasonCode(StrEnum):
    LIVE_EXECUTION_DISABLED = "LIVE_EXECUTION_DISABLED"
    STRATEGY_NOT_APPROVED = "STRATEGY_NOT_APPROVED"
    RISK_NOT_APPROVED = "RISK_NOT_APPROVED"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_STOP_PLACEMENT = "INVALID_STOP_PLACEMENT"
    INVALID_TARGET_PLACEMENT = "INVALID_TARGET_PLACEMENT"
    SYMBOL_MISMATCH = "SYMBOL_MISMATCH"
    SIDE_MISMATCH = "SIDE_MISMATCH"
    SOURCE_WINDOW_NOT_CLOSED = "SOURCE_WINDOW_NOT_CLOSED"
    MISSING_SOURCE_WINDOW = "MISSING_SOURCE_WINDOW"
    MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY"
    DUPLICATE_EXECUTION_INTENT = "DUPLICATE_EXECUTION_INTENT"
    UNSUPPORTED_ORDER_TYPE = "UNSUPPORTED_ORDER_TYPE"
    CONTRACT_MISMATCH = "CONTRACT_MISMATCH"
    EXECUTION_INTENT_READY = "EXECUTION_INTENT_READY"
