from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True, slots=True)
class LabelQualityGridConfig:
    config_id: str
    label_version: str
    horizon: int
    threshold: float
    take_profit_atr: float
    stop_loss_atr: float
    flat_threshold: float
    description: str
    risk_note: str
    anti_collapse_profile: str | None = None
    flat_bias_objective_enabled: bool = False
    bias_aware_objective_enabled: bool = False
    baseline_edge_objective_enabled: bool = False
    baseline_edge_focal_gamma: float | None = None
    baseline_edge_margin_penalty: float | None = None
    baseline_edge_entropy_penalty: float | None = None
    decision_calibration_enabled: bool = False
    decision_flat_if_max_prob_below: float | None = None
    decision_flat_if_margin_below: float | None = None
    decision_min_direction_prob: float | None = None
    decision_min_up_down_margin: float | None = None
    decision_down_boost: float | None = None
    decision_up_penalty: float | None = None
    decision_flat_boost: float | None = None
    decision_calibration_mode: str | None = None
    decision_fallback_to_raw: bool | None = None
    decision_max_flat_ratio: float | None = None
    decision_min_down_ratio_when_actual_down_high: float | None = None
    decision_min_up_ratio_when_actual_up_high: float | None = None
    decision_max_dominant_class_ratio: float | None = None
    decision_require_non_worse_baseline_edge: bool | None = None
    decision_baseline_edge_tolerance: float | None = None
    decision_actual_class_high_threshold: float | None = None
    decision_calibration: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        payload = {
            "config_id": self.config_id,
            "label_version": self.label_version,
            "horizon": self.horizon,
            "threshold": self.threshold,
            "take_profit_atr": self.take_profit_atr,
            "stop_loss_atr": self.stop_loss_atr,
            "flat_threshold": self.flat_threshold,
            "description": self.description,
            "risk_note": self.risk_note,
            "anti_collapse_profile": self.anti_collapse_profile,
            "flat_bias_objective_enabled": self.flat_bias_objective_enabled,
            "bias_aware_objective_enabled": self.bias_aware_objective_enabled,
            "baseline_edge_objective_enabled": self.baseline_edge_objective_enabled,
            "baseline_edge_focal_gamma": self.baseline_edge_focal_gamma,
            "baseline_edge_margin_penalty": self.baseline_edge_margin_penalty,
            "baseline_edge_entropy_penalty": self.baseline_edge_entropy_penalty,
            "decision_calibration_enabled": self.decision_calibration_enabled,
            "decision_flat_if_max_prob_below": self.decision_flat_if_max_prob_below,
            "decision_flat_if_margin_below": self.decision_flat_if_margin_below,
            "decision_min_direction_prob": self.decision_min_direction_prob,
            "decision_min_up_down_margin": self.decision_min_up_down_margin,
            "decision_down_boost": self.decision_down_boost,
            "decision_up_penalty": self.decision_up_penalty,
            "decision_flat_boost": self.decision_flat_boost,
            "decision_calibration_mode": self.decision_calibration_mode,
            "decision_fallback_to_raw": self.decision_fallback_to_raw,
            "decision_max_flat_ratio": self.decision_max_flat_ratio,
            "decision_min_down_ratio_when_actual_down_high": self.decision_min_down_ratio_when_actual_down_high,
            "decision_min_up_ratio_when_actual_up_high": self.decision_min_up_ratio_when_actual_up_high,
            "decision_max_dominant_class_ratio": self.decision_max_dominant_class_ratio,
            "decision_require_non_worse_baseline_edge": self.decision_require_non_worse_baseline_edge,
            "decision_baseline_edge_tolerance": self.decision_baseline_edge_tolerance,
            "decision_actual_class_high_threshold": self.decision_actual_class_high_threshold,
        }
        if self.decision_calibration_enabled:
            payload["decision_calibration"] = {
                "enabled": self.decision_calibration_enabled,
                "mode": self.decision_calibration_mode or "legacy_calibration",
                "flat_if_max_prob_below": self.decision_flat_if_max_prob_below,
                "flat_if_margin_below": self.decision_flat_if_margin_below,
                "min_direction_prob": self.decision_min_direction_prob,
                "min_up_down_margin": self.decision_min_up_down_margin,
                "down_boost": self.decision_down_boost,
                "up_penalty": self.decision_up_penalty,
                "flat_boost": self.decision_flat_boost,
                "fallback_to_raw": self.decision_fallback_to_raw,
                "max_flat_ratio": self.decision_max_flat_ratio,
                "min_down_ratio_when_actual_down_high": self.decision_min_down_ratio_when_actual_down_high,
                "min_up_ratio_when_actual_up_high": self.decision_min_up_ratio_when_actual_up_high,
                "max_dominant_class_ratio": self.decision_max_dominant_class_ratio,
                "require_non_worse_baseline_edge": self.decision_require_non_worse_baseline_edge,
                "baseline_edge_tolerance": self.decision_baseline_edge_tolerance,
                "actual_class_high_threshold": self.decision_actual_class_high_threshold,
            }
        return payload


class LabelQualityGridPlanner:
    PLANNER_NAME = "label_quality_grid_planner"
    PLANNER_VERSION = "ml30"

    def build_grid(self) -> dict[str, Any]:
        configs = [
            LabelQualityGridConfig(
                config_id="lv2_h08_thr03_tp10_sl10",
                label_version="lv2_h08_thr03_tp10_sl10",
                horizon=8,
                threshold=0.3,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.3,
                description="Short FV3-friendly horizon with looser threshold to reduce FLAT overprediction.",
                risk_note="Can reintroduce noisy directional labels if confidence remains weak.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h08_thr04_tp10_sl10",
                label_version="lv2_h08_thr04_tp10_sl10",
                horizon=8,
                threshold=0.4,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.4,
                description="Short horizon with symmetric TP/SL to reduce directional over-commitment.",
                risk_note="May stay noisy because horizon is still close to lv1.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h08_thr05_tp15_sl10",
                label_version="lv2_h08_thr05_tp15_sl10",
                horizon=8,
                threshold=0.5,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.5,
                description="Closest extension of lv1 with stricter flat separation.",
                risk_note="Can still collapse if feature set remains weak.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h04_thr02_tp08_sl08_ac",
                label_version="lv3_h04_thr02_tp08_sl08_ac",
                horizon=4,
                threshold=0.2,
                take_profit_atr=0.8,
                stop_loss_atr=0.8,
                flat_threshold=0.2,
                description="ML38.5 short intraday anti-collapse label: 1h horizon with low ATR threshold to increase directional samples.",
                risk_note="Can add noise; must be rejected if collapse/walk-forward gates fail.",
                anti_collapse_profile="intraday_directional_short",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h04_thr025_tp08_sl08_ac",
                label_version="lv3_h04_thr025_tp08_sl08_ac",
                horizon=4,
                threshold=0.25,
                take_profit_atr=0.8,
                stop_loss_atr=0.8,
                flat_threshold=0.25,
                description="ML38.5 short intraday anti-collapse label: 1h horizon with slightly stricter directional threshold.",
                risk_note="Can still be noisy on chop; only useful if probability separation improves.",
                anti_collapse_profile="intraday_directional_short",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h06_thr025_tp10_sl08_ac",
                label_version="lv3_h06_thr025_tp10_sl08_ac",
                horizon=6,
                threshold=0.25,
                take_profit_atr=1.0,
                stop_loss_atr=0.8,
                flat_threshold=0.25,
                description="ML38.5 medium intraday anti-collapse label: 1.5h horizon with asymmetric TP/SL to test directional sensitivity.",
                risk_note="Can over-favor fast directional moves; walk-forward must remain positive.",
                anti_collapse_profile="intraday_directional_medium",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h06_thr03_tp10_sl10_ac",
                label_version="lv3_h06_thr03_tp10_sl10_ac",
                horizon=6,
                threshold=0.3,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.3,
                description="ML38.5 medium intraday anti-collapse label: 1.5h horizon with balanced TP/SL.",
                risk_note="Should reduce label noise versus h04 but may still collapse if features are weak.",
                anti_collapse_profile="intraday_directional_medium",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h08_thr025_tp10_sl08_ac",
                label_version="lv3_h08_thr025_tp10_sl08_ac",
                horizon=8,
                threshold=0.25,
                take_profit_atr=1.0,
                stop_loss_atr=0.8,
                flat_threshold=0.25,
                description="ML38.5 h08 anti-collapse label: keep 2h horizon but lower flat threshold to reduce FLAT overprediction.",
                risk_note="Can increase false positives; baseline and walk-forward gates must stay strict.",
                anti_collapse_profile="intraday_directional_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h08_thr03_tp12_sl08_ac",
                label_version="lv3_h08_thr03_tp12_sl08_ac",
                horizon=8,
                threshold=0.3,
                take_profit_atr=1.2,
                stop_loss_atr=0.8,
                flat_threshold=0.3,
                description="ML38.5 h08 anti-collapse label: stronger reward target with tighter SL to test cleaner directional edges.",
                risk_note="Can reduce accepted signals if TP is too ambitious; evaluate by walk-forward only.",
                anti_collapse_profile="intraday_directional_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h06_thr035_tp12_sl08_cp",
                label_version="lv4_h06_thr035_tp12_sl08_cp",
                horizon=6,
                threshold=0.35,
                take_profit_atr=1.2,
                stop_loss_atr=0.8,
                flat_threshold=0.35,
                description="ML38.6 confidence/profitability retuning: h06, stricter margin, TP>SL to improve profit-aware gate.",
                risk_note="Can reduce signal count; reject if walk-forward or collapse gates fail.",
                anti_collapse_profile="confidence_profitability_h06",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h06_thr04_tp12_sl10_cp",
                label_version="lv4_h06_thr04_tp12_sl10_cp",
                horizon=6,
                threshold=0.4,
                take_profit_atr=1.2,
                stop_loss_atr=1.0,
                flat_threshold=0.4,
                description="ML38.6 confidence/profitability retuning: h06 with balanced stop and stronger directional threshold.",
                risk_note="May underfit weak symbols; must pass baseline/walk-forward gates without gate softening.",
                anti_collapse_profile="confidence_profitability_h06",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h08_thr035_tp12_sl08_cp",
                label_version="lv4_h08_thr035_tp12_sl08_cp",
                horizon=8,
                threshold=0.35,
                take_profit_atr=1.2,
                stop_loss_atr=0.8,
                flat_threshold=0.35,
                description="ML38.6 confidence/profitability retuning: h08 continuation from best h08/h06 candidates with cleaner TP/SL asymmetry.",
                risk_note="Can create false positives on chop; collapse gate remains mandatory.",
                anti_collapse_profile="confidence_profitability_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h08_thr04_tp15_sl10_cp",
                label_version="lv4_h08_thr04_tp15_sl10_cp",
                horizon=8,
                threshold=0.4,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.4,
                description="ML38.6 confidence/profitability retuning: h08 with stronger TP target for profit-aware filtering.",
                risk_note="Can lower hit rate; use only if walk-forward total R and PF improve.",
                anti_collapse_profile="confidence_profitability_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h12_thr04_tp12_sl08_cp",
                label_version="lv4_h12_thr04_tp12_sl08_cp",
                horizon=12,
                threshold=0.4,
                take_profit_atr=1.2,
                stop_loss_atr=0.8,
                flat_threshold=0.4,
                description="ML38.6 confidence/profitability retuning: h12 smoother horizon with TP>SL for better temporal stability.",
                risk_note="Can be too slow for intraday; reject if signal density collapses.",
                anti_collapse_profile="confidence_profitability_h12",
            ),
            LabelQualityGridConfig(
                config_id="lv4_h12_thr05_tp15_sl10_cp",
                label_version="lv4_h12_thr05_tp15_sl10_cp",
                horizon=12,
                threshold=0.5,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.5,
                description="ML38.6 confidence/profitability retuning: h12 stricter probability separation and 1.5R target.",
                risk_note="May increase FLAT/no-signal behavior; collapse diagnostics decide.",
                anti_collapse_profile="confidence_profitability_h12",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h12_thr03_tp10_sl10",
                label_version="lv2_h12_thr03_tp10_sl10",
                horizon=12,
                threshold=0.3,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.3,
                description="Mid horizon with looser threshold to restore directional sensitivity for FV3.",
                risk_note="Can increase false directional labels in choppy windows.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h12_thr04_tp15_sl10",
                label_version="lv2_h12_thr04_tp15_sl10",
                horizon=12,
                threshold=0.4,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.4,
                description="Mid horizon compromise to reduce FLAT bias without discarding BTC stability.",
                risk_note="May still overfit symbol-specific class balance.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h12_thr05_tp15_sl10",
                label_version="lv2_h12_thr05_tp15_sl10",
                horizon=12,
                threshold=0.5,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.5,
                description="Slightly longer horizon to smooth micro-noise in direction labels.",
                risk_note="Longer holding horizon can reduce signal density.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h16_thr04_tp15_sl10",
                label_version="lv2_h16_thr04_tp15_sl10",
                horizon=16,
                threshold=0.4,
                take_profit_atr=1.5,
                stop_loss_atr=1.0,
                flat_threshold=0.4,
                description="Longer horizon with moderate threshold to test whether FV3 benefits from smoother labels.",
                risk_note="Can suppress short-lived reversals if the horizon stays too slow.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h16_thr05_tp20_sl10",
                label_version="lv2_h16_thr05_tp20_sl10",
                horizon=16,
                threshold=0.5,
                take_profit_atr=2.0,
                stop_loss_atr=1.0,
                flat_threshold=0.5,
                description="Longer horizon with wider TP target for risk-first FV3 tuning.",
                risk_note="Can reduce sample count and amplify walk-forward instability.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h16_thr06_tp20_sl10",
                label_version="lv2_h16_thr06_tp20_sl10",
                horizon=16,
                threshold=0.6,
                take_profit_atr=2.0,
                stop_loss_atr=1.0,
                flat_threshold=0.6,
                description="More selective direction threshold with stronger TP asymmetry.",
                risk_note="Can over-prune labels and increase class sparsity.",
            ),
            LabelQualityGridConfig(
                config_id="lv2_h24_thr07_tp20_sl15",
                label_version="lv2_h24_thr07_tp20_sl15",
                horizon=24,
                threshold=0.7,
                take_profit_atr=2.0,
                stop_loss_atr=1.5,
                flat_threshold=0.7,
                description="Longer trend-oriented horizon for stability-focused experiments.",
                risk_note="Highest risk of low sample count and slower feedback loop.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h12_thr06_tp10_sl10",
                label_version="lv3_h12_thr06_tp10_sl10",
                horizon=12,
                threshold=0.6,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.6,
                description="Balanced horizon with stricter flat zone to reduce forced UP predictions.",
                risk_note="Can lower signal count if features remain weak.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h16_thr06_tp15_sl15",
                label_version="lv3_h16_thr06_tp15_sl15",
                horizon=16,
                threshold=0.6,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.6,
                description="Symmetric TP/SL with longer horizon to reduce directional skew.",
                risk_note="May trade less often because symmetric exits are stricter.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h20_thr07_tp15_sl15",
                label_version="lv3_h20_thr07_tp15_sl15",
                horizon=20,
                threshold=0.7,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.7,
                description="Broader no-trade zone with moderate reward/risk symmetry.",
                risk_note="Higher flat threshold can underfit if trend opportunities are sparse.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h24_thr08_tp20_sl20",
                label_version="lv3_h24_thr08_tp20_sl20",
                horizon=24,
                threshold=0.8,
                take_profit_atr=2.0,
                stop_loss_atr=2.0,
                flat_threshold=0.8,
                description="Strong separation and symmetric exits for collapse-resistant trend labels.",
                risk_note="Most selective config; risk of low sample count is high.",
            ),
            LabelQualityGridConfig(
                config_id="lv3_h32_thr08_tp20_sl15",
                label_version="lv3_h32_thr08_tp20_sl15",
                horizon=32,
                threshold=0.8,
                take_profit_atr=2.0,
                stop_loss_atr=1.5,
                flat_threshold=0.8,
                description="Long horizon with stronger flat zone and milder asymmetry than earlier configs.",
                risk_note="Long holding horizon can hurt responsiveness in choppy regimes.",
            ),
            LabelQualityGridConfig(
                config_id="lv5_h06_thr045_tp10_sl10_fb",
                label_version="lv5_h06_thr045_tp10_sl10_fb",
                horizon=6,
                threshold=0.45,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.45,
                description="ML38.9 flat/bias hardening: h06 with balanced TP/SL and stronger FLAT zone to reduce UP/DOWN top1 collapse.",
                risk_note="May reduce signal count; reject if baseline/walk-forward gates fail.",
                anti_collapse_profile="flat_bias_h06",
            ),
            LabelQualityGridConfig(
                config_id="lv5_h08_thr05_tp10_sl10_fb",
                label_version="lv5_h08_thr05_tp10_sl10_fb",
                horizon=8,
                threshold=0.50,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.50,
                description="ML38.9 flat/bias hardening: h08 with symmetric exits and stronger flat/no-trade separation.",
                risk_note="Useful only if FLAT top1 coverage improves without killing baseline edge.",
                anti_collapse_profile="flat_bias_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv5_h12_thr055_tp12_sl12_fb",
                label_version="lv5_h12_thr055_tp12_sl12_fb",
                horizon=12,
                threshold=0.55,
                take_profit_atr=1.2,
                stop_loss_atr=1.2,
                flat_threshold=0.55,
                description="ML38.9 flat/bias hardening: h12 smoother horizon with symmetric 1.2 ATR exits.",
                risk_note="Can become too selective; use quick-quality before full validation.",
                anti_collapse_profile="flat_bias_h12",
            ),
            LabelQualityGridConfig(
                config_id="lv5_h16_thr06_tp15_sl15_fb",
                label_version="lv5_h16_thr06_tp15_sl15_fb",
                horizon=16,
                threshold=0.60,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.60,
                description="ML38.9 flat/bias hardening: h16 conservative config for stronger no-trade/flat separation.",
                risk_note="Likely lower signal density; keep gates strict.",
                anti_collapse_profile="flat_bias_h16",
            ),
            LabelQualityGridConfig(
                config_id="lv6_h08_thr052_tp10_sl10_ba",
                label_version="lv6_h08_thr052_tp10_sl10_ba",
                horizon=8,
                threshold=0.52,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.52,
                description="ML38.9.1 bias-aware objective: h08, symmetric exits, stronger no-direction zone to reduce UP-dominance and restore FLAT/DOWN coverage.",
                risk_note="May reduce signal count; reject if baseline/walk-forward gates fail.",
                anti_collapse_profile="bias_aware_h08",
            ),
            LabelQualityGridConfig(
                config_id="lv6_h10_thr055_tp10_sl10_ba",
                label_version="lv6_h10_thr055_tp10_sl10_ba",
                horizon=10,
                threshold=0.55,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.55,
                description="ML38.9.1 bias-aware objective: h10 middle horizon to reduce noisy directional labels while keeping intraday responsiveness.",
                risk_note="Use as fast-debug config; reject if class distribution still collapses.",
                anti_collapse_profile="bias_aware_h10",
            ),
            LabelQualityGridConfig(
                config_id="lv6_h12_thr06_tp12_sl12_ba",
                label_version="lv6_h12_thr06_tp12_sl12_ba",
                horizon=12,
                threshold=0.60,
                take_profit_atr=1.2,
                stop_loss_atr=1.2,
                flat_threshold=0.60,
                description="ML38.9.1 bias-aware objective: h12 smoother horizon with balanced exits and stronger class-coverage objective.",
                risk_note="Main quick-quality candidate; do not accept if bias_gate/walk-forward fails.",
                anti_collapse_profile="bias_aware_h12",
            ),
            LabelQualityGridConfig(
                config_id="lv6_h16_thr065_tp15_sl15_ba",
                label_version="lv6_h16_thr065_tp15_sl15_ba",
                horizon=16,
                threshold=0.65,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.65,
                description="ML38.9.1 bias-aware objective: conservative h16 config for single-symbol full-period validation.",
                risk_note="Can become too selective; use after quick-quality improves.",
                anti_collapse_profile="bias_aware_h16",
            ),
            LabelQualityGridConfig(
                config_id="lv7_h08_thr052_tp10_sl10_be",
                label_version="lv7_h08_thr052_tp10_sl10_be",
                horizon=8,
                threshold=0.52,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.52,
                description="ML38.9.2 baseline-edge-aware balanced short horizon",
                risk_note="May still be rejected if baseline edge stays weak or collapse severity turns critical.",
                anti_collapse_profile="baseline_edge_h08",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.20,
                baseline_edge_margin_penalty=0.02,
                baseline_edge_entropy_penalty=0.01,
            ),
            LabelQualityGridConfig(
                config_id="lv7_h10_thr055_tp10_sl10_be",
                label_version="lv7_h10_thr055_tp10_sl10_be",
                horizon=10,
                threshold=0.55,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.55,
                description="ML38.9.2 baseline-edge-aware default quick-quality candidate",
                risk_note="Use as ML38.9.2 fast-debug and quick-quality shortlist; keep baseline and collapse gates strict.",
                anti_collapse_profile="baseline_edge_h10",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.25,
                baseline_edge_margin_penalty=0.02,
                baseline_edge_entropy_penalty=0.015,
            ),
            LabelQualityGridConfig(
                config_id="lv7_h12_thr06_tp12_sl12_be",
                label_version="lv7_h12_thr06_tp12_sl12_be",
                horizon=12,
                threshold=0.60,
                take_profit_atr=1.2,
                stop_loss_atr=1.2,
                flat_threshold=0.60,
                description="ML38.9.2 baseline-edge-aware longer confirmation candidate",
                risk_note="Can reduce signal density; keep walk-forward and baseline-edge gates unchanged.",
                anti_collapse_profile="baseline_edge_h12",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.30,
                baseline_edge_margin_penalty=0.015,
                baseline_edge_entropy_penalty=0.01,
            ),
            LabelQualityGridConfig(
                config_id="lv8_h10_thr055_tp10_sl10_cd",
                label_version="lv8_h10_thr055_tp10_sl10_cd",
                horizon=10,
                threshold=0.55,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.55,
                description="ML38.9.3 calibrated decision profile: uncertainty-to-FLAT, moderate down correction.",
                risk_note="Use calibrated decision diagnostics without softening collapse, bias, or baseline-edge gates.",
                anti_collapse_profile="calibrated_decision_h10",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.25,
                baseline_edge_margin_penalty=0.02,
                baseline_edge_entropy_penalty=0.015,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.42,
                decision_flat_if_margin_below=0.055,
                decision_min_direction_prob=0.40,
                decision_min_up_down_margin=0.030,
                decision_down_boost=0.015,
                decision_up_penalty=0.010,
                decision_flat_boost=0.010,
            ),
            LabelQualityGridConfig(
                config_id="lv8_h12_thr06_tp12_sl12_cd",
                label_version="lv8_h12_thr06_tp12_sl12_cd",
                horizon=12,
                threshold=0.60,
                take_profit_atr=1.2,
                stop_loss_atr=1.2,
                flat_threshold=0.60,
                description="ML38.9.3 calibrated decision profile: stronger uncertainty-to-FLAT for h12.",
                risk_note="Primary ML38.9.3 fast-debug and quick-quality candidate; keep strict gates unchanged.",
                anti_collapse_profile="calibrated_decision_h12",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.30,
                baseline_edge_margin_penalty=0.015,
                baseline_edge_entropy_penalty=0.01,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.43,
                decision_flat_if_margin_below=0.065,
                decision_min_direction_prob=0.405,
                decision_min_up_down_margin=0.035,
                decision_down_boost=0.020,
                decision_up_penalty=0.015,
                decision_flat_boost=0.015,
            ),
            LabelQualityGridConfig(
                config_id="lv8_h16_thr065_tp15_sl15_cd",
                label_version="lv8_h16_thr065_tp15_sl15_cd",
                horizon=16,
                threshold=0.65,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.65,
                description="ML38.9.3 calibrated decision profile: slower horizon with stronger no-direction filter.",
                risk_note="Use for one-symbol full validation after quick-quality; do not accept if walk-forward remains weak.",
                anti_collapse_profile="calibrated_decision_h16",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.30,
                baseline_edge_margin_penalty=0.015,
                baseline_edge_entropy_penalty=0.01,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.44,
                decision_flat_if_margin_below=0.070,
                decision_min_direction_prob=0.410,
                decision_min_up_down_margin=0.040,
                decision_down_boost=0.020,
                decision_up_penalty=0.020,
                decision_flat_boost=0.020,
            ),
            LabelQualityGridConfig(
                config_id="lv9_h08_thr052_tp10_sl10_bc",
                label_version="lv9_h08_thr052_tp10_sl10_bc",
                horizon=8,
                threshold=0.52,
                take_profit_atr=1.0,
                stop_loss_atr=1.0,
                flat_threshold=0.52,
                description="ML38.9.4 bounded calibration: h08 with distribution-safe raw-vs-calibrated decision selection.",
                risk_note="Keep collapse, bias, and baseline-edge gates strict; fallback to raw if calibration harms coverage or baseline edge.",
                anti_collapse_profile="bounded_calibration_h08",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.20,
                baseline_edge_margin_penalty=0.02,
                baseline_edge_entropy_penalty=0.01,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.42,
                decision_flat_if_margin_below=0.055,
                decision_min_direction_prob=0.40,
                decision_min_up_down_margin=0.030,
                decision_down_boost=0.015,
                decision_up_penalty=0.010,
                decision_flat_boost=0.010,
                decision_calibration_mode="bounded_calibration",
                decision_fallback_to_raw=True,
                decision_max_flat_ratio=0.45,
                decision_min_down_ratio_when_actual_down_high=0.12,
                decision_min_up_ratio_when_actual_up_high=0.12,
                decision_max_dominant_class_ratio=0.75,
                decision_require_non_worse_baseline_edge=True,
                decision_baseline_edge_tolerance=0.0025,
                decision_actual_class_high_threshold=0.25,
            ),
            LabelQualityGridConfig(
                config_id="lv9_h12_thr06_tp12_sl12_bc",
                label_version="lv9_h12_thr06_tp12_sl12_bc",
                horizon=12,
                threshold=0.60,
                take_profit_atr=1.2,
                stop_loss_atr=1.2,
                flat_threshold=0.60,
                description="ML38.9.4 bounded calibration: h12 with calibration guarded by distribution and baseline-edge checks.",
                risk_note="Primary ML38.9.4 fast-debug and quick-quality candidate; keep strict gates unchanged.",
                anti_collapse_profile="bounded_calibration_h12",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.30,
                baseline_edge_margin_penalty=0.015,
                baseline_edge_entropy_penalty=0.01,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.43,
                decision_flat_if_margin_below=0.065,
                decision_min_direction_prob=0.405,
                decision_min_up_down_margin=0.035,
                decision_down_boost=0.020,
                decision_up_penalty=0.015,
                decision_flat_boost=0.015,
                decision_calibration_mode="bounded_calibration",
                decision_fallback_to_raw=True,
                decision_max_flat_ratio=0.42,
                decision_min_down_ratio_when_actual_down_high=0.15,
                decision_min_up_ratio_when_actual_up_high=0.15,
                decision_max_dominant_class_ratio=0.72,
                decision_require_non_worse_baseline_edge=True,
                decision_baseline_edge_tolerance=0.0025,
                decision_actual_class_high_threshold=0.25,
            ),
            LabelQualityGridConfig(
                config_id="lv9_h16_thr065_tp15_sl15_bc",
                label_version="lv9_h16_thr065_tp15_sl15_bc",
                horizon=16,
                threshold=0.65,
                take_profit_atr=1.5,
                stop_loss_atr=1.5,
                flat_threshold=0.65,
                description="ML38.9.4 bounded calibration: h16 with conservative bounded selection for full single-symbol validation.",
                risk_note="Use after quick-quality; fallback to raw if calibration worsens class distribution or baseline edge.",
                anti_collapse_profile="bounded_calibration_h16",
                flat_bias_objective_enabled=True,
                bias_aware_objective_enabled=True,
                baseline_edge_objective_enabled=True,
                baseline_edge_focal_gamma=1.30,
                baseline_edge_margin_penalty=0.015,
                baseline_edge_entropy_penalty=0.01,
                decision_calibration_enabled=True,
                decision_flat_if_max_prob_below=0.44,
                decision_flat_if_margin_below=0.070,
                decision_min_direction_prob=0.410,
                decision_min_up_down_margin=0.040,
                decision_down_boost=0.020,
                decision_up_penalty=0.020,
                decision_flat_boost=0.020,
                decision_calibration_mode="bounded_calibration",
                decision_fallback_to_raw=True,
                decision_max_flat_ratio=0.40,
                decision_min_down_ratio_when_actual_down_high=0.15,
                decision_min_up_ratio_when_actual_up_high=0.15,
                decision_max_dominant_class_ratio=0.70,
                decision_require_non_worse_baseline_edge=True,
                decision_baseline_edge_tolerance=0.0025,
                decision_actual_class_high_threshold=0.25,
            ),
        ]
        return {
            "planner_name": self.PLANNER_NAME,
            "planner_version": self.PLANNER_VERSION,
            "config_count": len(configs),
            "configs": [config.to_dict() for config in configs],
        }
