"""Book-based trend and market state reading engine.

engine_analysis is a clean BOOK-L1 core that reads candles for a selected period
and classifies market state as UP, DOWN, FLAT, or UNKNOWN.

It must not produce trading signals.
"""

from app.engine_analysis.schemas import (
    BookEvidence,
    BookSource,
    ConfidenceDecomposition,
    EngineAnalysisCandle,
    EngineAnalysisEvidence,
    EngineAnalysisRegime,
    EngineAnalysisResult,
    EngineAnalysisSafety,
    TradeSignal,
)
from app.engine_analysis.analysis_contract import (
    MIN_FULL_ANALYSIS_CANDLES,
    RECOMMENDED_CONTEXT_CANDLES,
    AnalysisReadiness,
    AnalysisWindowConfig,
    analysis_readiness,
    interval_duration,
    parse_market_timestamp,
)
from app.engine_analysis.candle_morphology import (
    CandleDirection,
    CandleMorphology,
    analyze_candle_morphology,
    analyze_candle_window_morphology,
)
from app.engine_analysis.nison_candlestick_context import (
    NisonCandleContext,
    NisonWindowContext,
    analyze_nison_candle_context,
    analyze_nison_window_context,
)
from app.engine_analysis.nison_pattern_catalog import (
    CATALOG_DESCRIPTIONS,
    analyze_nison_pattern_catalog,
)
from app.engine_analysis.altunina_trend_context import (
    ALTUNINA_CORRECTION_LIMIT,
    FIBONACCI_PULLBACK_LEVELS,
    AltuninaStructureDirection,
    AltuninaTrendContext,
    ImpulseCorrectionSummary,
    PriceLeg,
    PriceLegDirection,
    SwingPoint,
    SwingPointType,
    TrendDurationClass,
    TrendDurationSummary,
    TrendHierarchyRole,
    TrendLineSummary,
    analyze_altunina_trend_context,
    analyze_impulse_correction,
    build_trend_line,
    build_price_legs,
    classify_trend_duration,
    classify_structure_direction,
    detect_swing_points,
    detect_volatility_aware_swing_points,
    normalize_swing_points,
)
from app.engine_analysis.schwager_range_context import (
    BreakoutConfirmationStatus,
    BreakoutConfirmationMethod,
    BreakoutContext,
    BreakoutDirection,
    FalseBreakoutConfirmationStatus,
    PolarityFlipContext,
    PolarityFlipStatus,
    SchwagerRangeContext,
    SupportResistanceZone,
    TradingRange,
    ZoneType,
    analyze_breakout_context,
    analyze_polarity_flip_context,
    analyze_schwager_range_context,
    build_support_resistance_zones,
    detect_trading_range,
)
from app.engine_analysis.unified_market_context import (
    UnifiedMarketContext,
    VolumeContext,
    build_unified_market_context,
)
from app.engine_analysis.technical_indicator_context import (
    IndicatorDirection,
    TechnicalIndicatorContext,
    analyze_technical_indicators,
)
from app.engine_analysis.market_hypothesis import (
    ContextualEventStatus,
    ContextualPatternEvent,
    FollowThroughStatus,
    HypothesisDirection,
    HypothesisStatus,
    HypothesisType,
    MarketHypothesis,
    MarketHypothesisResult,
    PatternDirection,
    PatternRole,
    analyze_market_hypotheses,
)
from app.engine_analysis.book_evidence_matrix import (
    BookAgreementState,
    BookEvidenceBucket,
    BookEvidenceMatrix,
    ConfluenceConflictSummary,
    DirectionalEvidenceBalance,
    EvidenceConflictLevel,
    EvidenceCoverageLevel,
    EvidenceDirection,
    analyze_book_evidence_matrix,
    build_book_evidence_bucket,
    build_confluence_conflict_summary,
    build_directional_evidence_balance,
)
from app.engine_analysis.regime_composer import (
    RegimeCandidateScores,
    RegimeComposerOutput,
    RegimeComposerStatus,
    RegimeConfidenceLevel,
    RegimeDecisionSource,
    RegimeDecisionTrace,
    compose_engine_analysis_result,
    compose_regime_from_matrix,
    score_regime_candidates,
)
from app.engine_analysis.engine import (
    EngineAnalysisFacadeOutput,
    normalize_candle_row,
    normalize_candles,
    run_engine_analysis,
    run_engine_analysis_from_rows,
)
from app.engine_analysis.json_export import (
    build_engine_analysis_json_payload,
    build_engine_analysis_preview,
    save_engine_analysis_json,
)
from app.engine_analysis.data_source_boundary import (
    CandleDataBatch,
    CandleDataBoundaryResult,
    CandleDataBoundaryStatus,
    CandleDataProvider,
    CandleDataQualityFlag,
    CandleDataRequest,
    build_candle_data_batch,
    run_engine_analysis_from_batch,
    run_engine_analysis_from_provider,
    validate_candle_data_request,
)
from app.engine_analysis.multi_timeframe import (
    MultiTimeframeResult,
    TimeframeAlignment,
    run_multi_timeframe_engine_analysis,
)
from app.engine_analysis.oos_validation import (
    OOSValidationResult,
    ValidationLabelSource,
    build_manual_annotation_template,
    deduplicate_validation_items,
    run_balanced_oos_validation,
)
from app.engine_analysis.analysis_snapshot import (
    AnalysisSnapshot,
    AnalysisSnapshotStatus,
    analysis_snapshot_id,
)
from app.engine_analysis.analysis_snapshot_store import AnalysisSnapshotStore
from app.engine_analysis.market_data_adapter import MarketDataAdapter
from app.engine_analysis.online_config import OnlineAnalysisConfig
from app.engine_analysis.online_runner import OnlineAnalysisRunner

__all__ = [
    "MIN_FULL_ANALYSIS_CANDLES",
    "RECOMMENDED_CONTEXT_CANDLES",
    "AnalysisReadiness",
    "AnalysisWindowConfig",
    "analysis_readiness",
    "interval_duration",
    "parse_market_timestamp",
    "BookEvidence",
    "BookSource",
    "ConfidenceDecomposition",
    "EngineAnalysisCandle",
    "EngineAnalysisEvidence",
    "EngineAnalysisRegime",
    "EngineAnalysisResult",
    "EngineAnalysisSafety",
    "TradeSignal",
    "CandleDirection",
    "CandleMorphology",
    "NisonCandleContext",
    "NisonWindowContext",
    "analyze_candle_morphology",
    "analyze_candle_window_morphology",
    "analyze_nison_candle_context",
    "analyze_nison_window_context",
    "CATALOG_DESCRIPTIONS",
    "analyze_nison_pattern_catalog",
    "ALTUNINA_CORRECTION_LIMIT",
    "FIBONACCI_PULLBACK_LEVELS",
    "AltuninaStructureDirection",
    "AltuninaTrendContext",
    "ImpulseCorrectionSummary",
    "PriceLeg",
    "PriceLegDirection",
    "SwingPoint",
    "SwingPointType",
    "TrendDurationClass",
    "TrendDurationSummary",
    "TrendHierarchyRole",
    "TrendLineSummary",
    "analyze_altunina_trend_context",
    "analyze_impulse_correction",
    "build_trend_line",
    "build_price_legs",
    "classify_trend_duration",
    "classify_structure_direction",
    "detect_swing_points",
    "detect_volatility_aware_swing_points",
    "normalize_swing_points",
    "BreakoutConfirmationStatus",
    "BreakoutConfirmationMethod",
    "BreakoutContext",
    "BreakoutDirection",
    "FalseBreakoutConfirmationStatus",
    "PolarityFlipContext",
    "PolarityFlipStatus",
    "SchwagerRangeContext",
    "SupportResistanceZone",
    "TradingRange",
    "ZoneType",
    "analyze_breakout_context",
    "analyze_polarity_flip_context",
    "analyze_schwager_range_context",
    "build_support_resistance_zones",
    "detect_trading_range",
    "UnifiedMarketContext",
    "VolumeContext",
    "build_unified_market_context",
    "IndicatorDirection",
    "TechnicalIndicatorContext",
    "analyze_technical_indicators",
    "ContextualEventStatus",
    "ContextualPatternEvent",
    "FollowThroughStatus",
    "HypothesisDirection",
    "HypothesisStatus",
    "HypothesisType",
    "MarketHypothesis",
    "MarketHypothesisResult",
    "PatternDirection",
    "PatternRole",
    "analyze_market_hypotheses",
    "BookAgreementState",
    "BookEvidenceBucket",
    "BookEvidenceMatrix",
    "ConfluenceConflictSummary",
    "DirectionalEvidenceBalance",
    "EvidenceConflictLevel",
    "EvidenceCoverageLevel",
    "EvidenceDirection",
    "analyze_book_evidence_matrix",
    "build_book_evidence_bucket",
    "build_confluence_conflict_summary",
    "build_directional_evidence_balance",
    "RegimeCandidateScores",
    "RegimeComposerOutput",
    "RegimeComposerStatus",
    "RegimeConfidenceLevel",
    "RegimeDecisionSource",
    "RegimeDecisionTrace",
    "compose_engine_analysis_result",
    "compose_regime_from_matrix",
    "score_regime_candidates",
    "EngineAnalysisFacadeOutput",
    "normalize_candle_row",
    "normalize_candles",
    "run_engine_analysis",
    "run_engine_analysis_from_rows",
    "build_engine_analysis_json_payload",
    "build_engine_analysis_preview",
    "save_engine_analysis_json",
    "CandleDataBatch",
    "CandleDataBoundaryResult",
    "CandleDataBoundaryStatus",
    "CandleDataProvider",
    "CandleDataQualityFlag",
    "CandleDataRequest",
    "build_candle_data_batch",
    "run_engine_analysis_from_batch",
    "run_engine_analysis_from_provider",
    "validate_candle_data_request",
    "MultiTimeframeResult",
    "TimeframeAlignment",
    "run_multi_timeframe_engine_analysis",
    "OOSValidationResult",
    "ValidationLabelSource",
    "build_manual_annotation_template",
    "deduplicate_validation_items",
    "run_balanced_oos_validation",
    "AnalysisSnapshot",
    "AnalysisSnapshotStatus",
    "analysis_snapshot_id",
    "AnalysisSnapshotStore",
    "MarketDataAdapter",
    "OnlineAnalysisConfig",
    "OnlineAnalysisRunner",
]
