"""ML38.10.70 no-run readiness evidence for one future SOLUSDT rerun."""

from __future__ import annotations


post_field_contract_rerun_readiness = {
    "diagnostic_name": "post_field_contract_rerun_readiness",
    "diagnostic_version": "ml38.10.70",
    "execution_mode": "READINESS_NO_RUN_NO_WRAPPER_NO_QUICK_QUALITY",
    "previous_stage_summary": {
        "previous_stage": "ML38.10.69",
        "previous_decision": "SIDECAR_FIELD_CONTRACT_IMPLEMENTED_TESTED_NO_REAL_RUN",
        "previous_full_pytest": "1160 passed, 0 skipped, 0 warnings",
        "previous_full_pytest_exit_code": 0,
        "previous_full_pytest_log": r"D:\disk_E\game_projects\traders\traders-ml-run-logs\full_pytest_ml38_10_69_static_probe_fix_20260707_235953.log",
        "commit_performed_after_ml38_10_69": False,
        "planning_update_performed_after_ml38_10_69": False,
        "snapshot_performed_after_ml38_10_69": False,
    },
    "ml38_10_69_contract_evidence": {
        "field_contract_version": "ml38.10.69",
        "raw_probabilities_present_in_future_sidecar_contract": True,
        "raw_probability_source": "direction_logits_temperature_1_softmax",
        "calibrated_probabilities_present_in_future_sidecar_contract": True,
        "calibrated_probability_source": "current_temperature_scaled_output",
        "actual_label_present_in_future_sidecar_contract": True,
        "actual_label_source": "source_row.direction_label",
        "legacy_probability_aliases_preserved": True,
        "legacy_aliases": "prob_down/prob_flat/prob_up",
        "prediction_layers_present": True,
        "prediction_layers": ["raw", "calibrated", "sidecar_selected"],
        "downstream_policy_available_in_writer": False,
        "downstream_policy_not_conflated_with_sidecar_argmax": True,
        "row_alignment_key_present": True,
        "row_alignment_key_definition": "sha256 canonical JSON from candidate/symbol/interval/horizon/split/global index/split index/timestamp",
        "fail_closed_validation_before_artifact_directory": True,
        "full_pytest_evidence_available": True,
        "field_contract_tested": True,
    },
    "static_probe_fix_evidence": {
        "ml38_10_55_probe_updated": True,
        "actual_label_export_allowed_by_field_contract": True,
        "actual_label_target_only": True,
        "actual_label_used_for_prediction": False,
        "label_substitution_detected": False,
        "prediction_label_source": "probability_argmax",
        "sidecar_writer_contract_changed_during_static_probe_fix": False,
    },
    "wrapper_readiness": {
        "wrapper_file_present": True,
        "wrapper_requires_execute_flag": True,
        "wrapper_requires_i_understand_flag": True,
        "wrapper_targets_solusdt_quick_quality_only": True,
        "wrapper_command_expected": "python run_solusdt_quick_quality_once.py --execute --i-understand-this-runs-real-quick-quality",
        "wrapper_requires_clean_worktree_at_execution": True,
        "current_dirty_worktree_would_be_rejected_by_wrapper": True,
        "wrapper_run_during_readiness": False,
        "quick_quality_run_during_readiness": False,
        "readiness_confidence": "HIGH",
    },
    "expected_next_real_run_scope": {
        "next_real_run_requires_separate_user_approval": True,
        "allowed_scope_after_approval": "one SOLUSDT quick-quality wrapper run only",
        "allowed_command_after_approval": "python run_solusdt_quick_quality_once.py --execute --i-understand-this-runs-real-quick-quality",
        "disallowed_in_next_real_run": [
            "BTC", "ETH", "multi-symbol", "clean", "fast-debug", "sequence",
            "DB writes outside normal pipeline", "cascade/outcome", "production-like recompute",
        ],
        "expected_artifact_goal": "generate future SOLUSDT sidecars with ML38.10.69 field contract",
        "expected_validation_after_real_run": [
            "validate raw probabilities present",
            "validate calibrated probabilities present",
            "validate actual_label present",
            "validate row_alignment_key present and unique",
            "validate prediction layers present",
            "validate no label substitution",
            "validate exact-byte summary hash/size",
            "validate LF-only JSONL",
            "validate ZIP if created",
        ],
        "actual_real_run_authorized_now": False,
    },
    "h08_risk_assessment": {
        "h08_known_issue_present": True,
        "h08_candidate_boundary_total": 6485,
        "h08_expected_global_denominator": 6481,
        "h08_delta_rows": 4,
        "h08_fix_applied": False,
        "h08_blocks_readiness": False,
        "h08_expected_behavior_if_rerun": "may produce one failed h08 candidate but should not block 45 h12 sidecar sets if prior behavior remains",
        "h08_recommendation": "keep_separately_scoped",
        "h08_reasoning": "The known +4 boundary mismatch is isolated to h08; prior behavior still produced the 45 h12 sidecar sets needed for this rerun goal.",
    },
    "dirty_worktree_policy": {
        "worktree_dirty_expected": True,
        "dirty_reason": "uncommitted ML38.10.69 implementation by user workflow rule",
        "commit_required_before_readiness": False,
        "commit_required_before_real_run": "USER_DECISION",
        "unexpected_runtime_artifacts_detected": False,
        "dirty_files_classified_as_ml38_10_69_only": True,
        "dirty_worktree_blocks_readiness": False,
        "dirty_worktree_blocks_future_real_run": "USER_DECISION",
        "reproducibility_risk": "A real run from uncommitted code is harder to reproduce exactly; the current wrapper also rejects a dirty worktree until the user chooses a compatible workflow.",
    },
    "readiness_gate": {
        "ml38_10_69_full_pytest_passed": True,
        "sidecar_field_contract_implemented": True,
        "static_probe_regression_fixed": True,
        "wrapper_safety_flags_present": True,
        "real_run_not_executed": True,
        "quick_quality_not_executed": True,
        "h08_assessed": True,
        "dirty_worktree_assessed": True,
        "unexpected_runtime_artifacts_absent": True,
        "next_run_scope_defined": True,
        "next_run_requires_separate_approval": True,
        "ready_for_separately_approved_rerun": True,
    },
    "guardrails": {
        "training_run_during_readiness": False,
        "wrapper_execute_used_during_readiness": False,
        "quick_quality_rerun_during_readiness": False,
        "run_fv3_cached_tuning_used_during_readiness": False,
        "db_writes_during_readiness": False,
        "ml_labels_writes_during_readiness": False,
        "ml_predictions_writes_during_readiness": False,
        "labels_builders_gates_model_logic_changed": False,
        "class_weights_changed": False,
        "training_objective_changed": False,
        "production_calibration_policy_changed": False,
        "directional_confidence_floor_implemented": False,
        "flat_override_implemented": False,
        "h08_fix_applied": False,
        "existing_real_artifacts_mutated": False,
        "new_real_sidecars_created": False,
        "new_zip_created": False,
        "archive_recovery_performed": False,
        "cascade_outcome_run": False,
        "production_like_recompute": False,
        "tradable_edge_confirmed": False,
        "commit_performed": False,
        "planning_update_performed": False,
        "snapshot_performed": False,
    },
    "decision_gate": {
        "readiness_diagnostic_completed": True,
        "ml38_10_69_evidence_complete": True,
        "wrapper_readiness_confirmed": True,
        "h08_blocks_next_step": False,
        "dirty_worktree_blocks_next_step": False,
        "next_action_selected": True,
        "real_run_authorized_now": False,
        "decision": "READY_FOR_SEPARATELY_APPROVED_SOLUSDT_QUICK_QUALITY_RERUN",
        "next_allowed_stage": "ML38.10.71 — separately approved SOLUSDT quick-quality rerun",
    },
    "next_step_plan": [
        "Obtain separate user approval for exactly one SOLUSDT quick-quality wrapper run.",
        "Resolve the wrapper clean-worktree precondition according to the user's explicit workflow decision.",
        "After a successful run, validate the ML38.10.69 sidecar field contract and exact-byte artifacts.",
    ],
    "decision": ["READY_FOR_SEPARATELY_APPROVED_SOLUSDT_QUICK_QUALITY_RERUN"],
}


diagnostic = post_field_contract_rerun_readiness
