"""Stable public vocabularies for the local position domain."""
from enum import StrEnum


class PositionStatus(StrEnum):
    PENDING_OPEN = "PENDING_OPEN"
    OPEN = "OPEN"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    DISABLED = "DISABLED"


class PositionSide(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class PositionFillAction(StrEnum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"


class PositionReasonCode(StrEnum):
    POSITION_READY = "POSITION_READY"
    POSITION_PENDING_OPEN = "POSITION_PENDING_OPEN"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_PARTIALLY_CLOSED = "POSITION_PARTIALLY_CLOSED"
    POSITION_CLOSED = "POSITION_CLOSED"
    POSITION_CANCELLED = "POSITION_CANCELLED"
    LIVE_POSITION_MANAGEMENT_DISABLED = "LIVE_POSITION_MANAGEMENT_DISABLED"
    EXECUTION_INTENT_NOT_READY = "EXECUTION_INTENT_NOT_READY"
    EXECUTION_ACK_NOT_ACKNOWLEDGED = "EXECUTION_ACK_NOT_ACKNOWLEDGED"
    EXECUTION_CONTRACT_MISMATCH = "EXECUTION_CONTRACT_MISMATCH"
    MODE_MISMATCH = "MODE_MISMATCH"
    SYMBOL_MISMATCH = "SYMBOL_MISMATCH"
    SIDE_MISMATCH = "SIDE_MISMATCH"
    INVALID_INITIAL_QUANTITY = "INVALID_INITIAL_QUANTITY"
    INVALID_OPEN_QUANTITY = "INVALID_OPEN_QUANTITY"
    PARTIAL_OPEN_FILL_UNSUPPORTED = "PARTIAL_OPEN_FILL_UNSUPPORTED"
    INVALID_CLOSE_QUANTITY = "INVALID_CLOSE_QUANTITY"
    INVALID_ENTRY_PRICE = "INVALID_ENTRY_PRICE"
    INVALID_MARK_PRICE = "INVALID_MARK_PRICE"
    INVALID_CLOSE_PRICE = "INVALID_CLOSE_PRICE"
    INVALID_FEE = "INVALID_FEE"
    INVALID_STOP_PLACEMENT = "INVALID_STOP_PLACEMENT"
    INVALID_TARGET_PLACEMENT = "INVALID_TARGET_PLACEMENT"
    MISSING_SOURCE_WINDOW = "MISSING_SOURCE_WINDOW"
    SOURCE_WINDOW_NOT_CLOSED = "SOURCE_WINDOW_NOT_CLOSED"
    DUPLICATE_POSITION = "DUPLICATE_POSITION"
    DUPLICATE_POSITION_EVENT = "DUPLICATE_POSITION_EVENT"
    POSITION_ALREADY_TERMINAL = "POSITION_ALREADY_TERMINAL"
    INVALID_POSITION_TRANSITION = "INVALID_POSITION_TRANSITION"
    POSITION_ID_MISMATCH = "POSITION_ID_MISMATCH"
    OUT_OF_ORDER_POSITION_EVENT = "OUT_OF_ORDER_POSITION_EVENT"
    UNSUPPORTED_FILL_ACTION = "UNSUPPORTED_FILL_ACTION"
    POSITION_STORE_CONFLICT = "POSITION_STORE_CONFLICT"
