"""Stable diagnostic reason vocabulary for ENGINE-STRATEGY-01."""

from enum import StrEnum


class StrategyReasonCode(StrEnum):
    STRATEGY_ALLOW_GOOD_SETUP = "STRATEGY_ALLOW_GOOD_SETUP"
    STRATEGY_ALLOW_ACCEPTABLE_SETUP = "STRATEGY_ALLOW_ACCEPTABLE_SETUP"
    STRATEGY_REJECT_NO_SETUP = "STRATEGY_REJECT_NO_SETUP"
    STRATEGY_REJECT_SETUP_INVALID = "STRATEGY_REJECT_SETUP_INVALID"
    STRATEGY_REJECT_WEAK_QUALITY = "STRATEGY_REJECT_WEAK_QUALITY"
    STRATEGY_REJECT_POOR_OR_INVALID_QUALITY = "STRATEGY_REJECT_POOR_OR_INVALID_QUALITY"
    STRATEGY_REJECT_UNKNOWN_QUALITY = "STRATEGY_REJECT_UNKNOWN_QUALITY"
    STRATEGY_REJECT_NEUTRAL_DIRECTION = "STRATEGY_REJECT_NEUTRAL_DIRECTION"
    STRATEGY_REJECT_UNSUPPORTED_SETUP_TYPE = "STRATEGY_REJECT_UNSUPPORTED_SETUP_TYPE"
    STRATEGY_REJECT_HARD_INVALIDATION = "STRATEGY_REJECT_HARD_INVALIDATION"
    STRATEGY_REJECT_CONFLICTING_CONTEXT = "STRATEGY_REJECT_CONFLICTING_CONTEXT"
    STRATEGY_WAIT_FOR_CONFIRMATION = "STRATEGY_WAIT_FOR_CONFIRMATION"
    STRATEGY_WAIT_WEAK_BUT_STRUCTURED = "STRATEGY_WAIT_WEAK_BUT_STRUCTURED"
    STRATEGY_NO_DECISION_NO_SETUP = "STRATEGY_NO_DECISION_NO_SETUP"
    STRATEGY_ERROR_PROCESSING_FAILED = "STRATEGY_ERROR_PROCESSING_FAILED"
    STRATEGY_NO_FUTURE_BARS_USED = "STRATEGY_NO_FUTURE_BARS_USED"
    STRATEGY_NOT_EXECUTABLE = "STRATEGY_NOT_EXECUTABLE"
    STRATEGY_REQUIRES_RISK_REVIEW = "STRATEGY_REQUIRES_RISK_REVIEW"
