"""Research-only strategy classifications; none is an execution command."""

from enum import StrEnum


class StrategyType(StrEnum):
    SCALP_TREND_PULLBACK_RESEARCH = "SCALP_TREND_PULLBACK_RESEARCH"
    SCALP_BREAKOUT_RESEARCH = "SCALP_BREAKOUT_RESEARCH"
    SCALP_BREAKOUT_RETEST_RESEARCH = "SCALP_BREAKOUT_RETEST_RESEARCH"
    SCALP_RANGE_BOUNCE_RESEARCH = "SCALP_RANGE_BOUNCE_RESEARCH"
    SCALP_LIQUIDITY_SWEEP_RESEARCH = "SCALP_LIQUIDITY_SWEEP_RESEARCH"
    SCALP_MOMENTUM_CONTINUATION_RESEARCH = "SCALP_MOMENTUM_CONTINUATION_RESEARCH"
    SCALP_COMPRESSION_BREAK_RESEARCH = "SCALP_COMPRESSION_BREAK_RESEARCH"
    TREND_CONTINUATION_RESEARCH = "TREND_CONTINUATION_RESEARCH"
    BREAKOUT_CONTINUATION_RESEARCH = "BREAKOUT_CONTINUATION_RESEARCH"
    PULLBACK_CONTINUATION_RESEARCH = "PULLBACK_CONTINUATION_RESEARCH"
    RANGE_REJECTION_RESEARCH = "RANGE_REJECTION_RESEARCH"
    FALSE_BREAKOUT_REVERSAL_RESEARCH = "FALSE_BREAKOUT_REVERSAL_RESEARCH"
    MOMENTUM_EXHAUSTION_RESEARCH = "MOMENTUM_EXHAUSTION_RESEARCH"
    NO_STRATEGY = "NO_STRATEGY"


SETUP_TO_STRATEGY_TYPE = {
    "SCALP_TREND_PULLBACK": StrategyType.SCALP_TREND_PULLBACK_RESEARCH.value,
    "SCALP_BREAKOUT": StrategyType.SCALP_BREAKOUT_RESEARCH.value,
    "SCALP_BREAKOUT_RETEST": StrategyType.SCALP_BREAKOUT_RETEST_RESEARCH.value,
    "SCALP_RANGE_BOUNCE": StrategyType.SCALP_RANGE_BOUNCE_RESEARCH.value,
    "SCALP_LIQUIDITY_SWEEP": StrategyType.SCALP_LIQUIDITY_SWEEP_RESEARCH.value,
    "SCALP_MOMENTUM_CONTINUATION": StrategyType.SCALP_MOMENTUM_CONTINUATION_RESEARCH.value,
    "SCALP_COMPRESSION_BREAK": StrategyType.SCALP_COMPRESSION_BREAK_RESEARCH.value,
    "TREND_CONTINUATION": StrategyType.TREND_CONTINUATION_RESEARCH.value,
    "BREAKOUT_CONTINUATION": StrategyType.BREAKOUT_CONTINUATION_RESEARCH.value,
    "PULLBACK_CONTINUATION": StrategyType.PULLBACK_CONTINUATION_RESEARCH.value,
    "RANGE_REJECTION": StrategyType.RANGE_REJECTION_RESEARCH.value,
    "FALSE_BREAKOUT_REVERSAL": StrategyType.FALSE_BREAKOUT_REVERSAL_RESEARCH.value,
    "MOMENTUM_EXHAUSTION": StrategyType.MOMENTUM_EXHAUSTION_RESEARCH.value,
}
