"""Research-only strategy classifications; none is an execution command."""

from enum import StrEnum


class StrategyType(StrEnum):
    TREND_CONTINUATION_RESEARCH = "TREND_CONTINUATION_RESEARCH"
    BREAKOUT_CONTINUATION_RESEARCH = "BREAKOUT_CONTINUATION_RESEARCH"
    PULLBACK_CONTINUATION_RESEARCH = "PULLBACK_CONTINUATION_RESEARCH"
    RANGE_REJECTION_RESEARCH = "RANGE_REJECTION_RESEARCH"
    FALSE_BREAKOUT_REVERSAL_RESEARCH = "FALSE_BREAKOUT_REVERSAL_RESEARCH"
    MOMENTUM_EXHAUSTION_RESEARCH = "MOMENTUM_EXHAUSTION_RESEARCH"
    NO_STRATEGY = "NO_STRATEGY"


SETUP_TO_STRATEGY_TYPE = {
    "TREND_CONTINUATION": StrategyType.TREND_CONTINUATION_RESEARCH.value,
    "BREAKOUT_CONTINUATION": StrategyType.BREAKOUT_CONTINUATION_RESEARCH.value,
    "PULLBACK_CONTINUATION": StrategyType.PULLBACK_CONTINUATION_RESEARCH.value,
    "RANGE_REJECTION": StrategyType.RANGE_REJECTION_RESEARCH.value,
    "FALSE_BREAKOUT_REVERSAL": StrategyType.FALSE_BREAKOUT_REVERSAL_RESEARCH.value,
    "MOMENTUM_EXHAUSTION": StrategyType.MOMENTUM_EXHAUSTION_RESEARCH.value,
}
